# Python Pandas 
In Part we are going to learn about

Pandas Dataframe
Pandas Series
Pandas Basic Operations

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in /opt/anaconda3/lib/python3.14/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import numpy as np
import pandas as pd

In [13]:
data_to_dataframes=np.arange(0,30).reshape(6,5)
print(data_to_dataframes)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

In [16]:
import numpy as np
import pandas as pd

# 5 rows and 6 columns requires exactly 30 data points (0 to 29)
df = pd.DataFrame(
    data=np.arange(0, 30).reshape(5, 6),
    index=["Emp_01", "Emp_02", "Emp_03", "Emp_04", "Emp_05"],
    columns=[
        "Age",
        "Experience_Years",
        "Projects_Completed",
        "Performance_Score",
        "Monthly_Salary_K",
        "Training_Hours",
    ],
)

print(df)

        Age  Experience_Years  Projects_Completed  Performance_Score  \
Emp_01    0                 1                   2                  3
Emp_02    6                 7                   8                  9
Emp_03   12                13                  14                 15
Emp_04   18                19                  20                 21
Emp_05   24                25                  26                 27

        Monthly_Salary_K  Training_Hours
Emp_01                 4               5
Emp_02                10              11
Emp_03                16              17
Emp_04                22              23
Emp_05                28              29

In [17]:
df.head()

,Age,Experience_Years,Projects_Completed,Performance_Score,Monthly_Salary_K,Training_Hours
Emp_01,0,1,2,3,4,5
Emp_02,6,7,8,9,10,11
Emp_03,12,13,14,15,16,17
Emp_04,18,19,20,21,22,23
Emp_05,24,25,26,27,28,29

In [18]:
df.tail()

,Age,Experience_Years,Projects_Completed,Performance_Score,Monthly_Salary_K,Training_Hours
Emp_01,0,1,2,3,4,5
Emp_02,6,7,8,9,10,11
Emp_03,12,13,14,15,16,17
Emp_04,18,19,20,21,22,23
Emp_05,24,25,26,27,28,29

In [19]:
type(df)

pandas.DataFrame

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, Emp_01 to Emp_05
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 5 non-null      int64
 1   Experience_Years    5 non-null      int64
 2   Projects_Completed  5 non-null      int64
 3   Performance_Score   5 non-null      int64
 4   Monthly_Salary_K    5 non-null      int64
 5   Training_Hours      5 non-null      int64
dtypes: int64(6)
memory usage: 310.0 bytes

In [21]:
df.describe()

,Age,Experience_Years,Projects_Completed,Performance_Score,Monthly_Salary_K,Training_Hours
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,12.000000,13.000000,14.000000,15.000000,16.000000,17.000000
std,9.486833,9.486833,9.486833,9.486833,9.486833,9.486833
min,0.000000,1.000000,2.000000,3.000000,4.000000,5.000000
25%,6.000000,7.000000,8.000000,9.000000,10.000000,11.000000
50%,12.000000,13.000000,14.000000,15.000000,16.000000,17.000000
75%,18.000000,19.000000,20.000000,21.000000,22.000000,23.000000
max,24.000000,25.000000,26.000000,27.000000,28.000000,29.000000


 ## Indexing
 ## columnname,rowindex[loc],rowindex columnindex number[.iloc]

In [22]:
df.head()

,Age,Experience_Years,Projects_Completed,Performance_Score,Monthly_Salary_K,Training_Hours
Emp_01,0,1,2,3,4,5
Emp_02,6,7,8,9,10,11
Emp_03,12,13,14,15,16,17
Emp_04,18,19,20,21,22,23
Emp_05,24,25,26,27,28,29

In [27]:
df['Age']

Emp_01     0
Emp_02     6
Emp_03    12
Emp_04    18
Emp_05    24
Name: Age, dtype: int64

In [29]:
type(df['Age'])

pandas.Series

In [32]:
df.loc['Emp_01']

Age                   0
Experience_Years      1
Projects_Completed    2
Performance_Score     3
Monthly_Salary_K      4
Training_Hours        5
Name: Emp_01, dtype: int64

In [39]:
type(df.loc['Emp_01'])

pandas.Series

In [34]:
df.iloc[2:4,0:2]

        Age  Experience_Years
Emp_03   12                13
Emp_04   18                19

In [35]:
df.value_counts()

Age  Experience_Years  Projects_Completed  Performance_Score  Monthly_Salary_K  Training_Hours
0    1                 2                   3                  4                 5                 1
6    7                 8                   9                  10                11                1
12   13                14                  15                 16                17                1
18   19                20                  21                 22                23                1
24   25                26                  27                 28                29                1
Name: count, dtype: int64

In [38]:
df['Age'].unique()

array([ 0,  6, 12, 18, 24])

In [ ]:
pd.read_html()